steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/trans-airfoil-449223-q8/changedetection', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/trans-airfoil-449223-q8/changedetection']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'changedetection'
      - '--image'
      - 'gcr.io/trans-airfoil-449223-q8/changedetection'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'

logsBucket: "gs://versterrewebsitechange/data"  # ✅ Correct placement

options:
  logging: CLOUD_LOGGING_ONLY  # Optional: Stores logs only in Cloud Logging
