steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'rsync', '-r', './versterre/', 'gs://versterrewebsitechange/data']

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'us-central1-docker.pkg.dev/trans-airfoil-449223-q8/changedetection-repo/changedetection'
    ]

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'changedetection'
      - '--image'
      - 'us-central1-docker.pkg.dev/trans-airfoil-449223-q8/changedetection-repo/changedetection'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'  # Remove if authentication is required


logsBucket: "gs://versterrewebsitechange/data"  # Store build logs in this bucket



timeout: 1200s  # Optional: Customize timeout duration as needed

