steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/trans-airfoil-449223-q8/my-docker-repo/changedetection', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/trans-airfoil-449223-q8/my-docker-repo/changedetection']

  # Step 3: Deploy the image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'changedetection'
      - '--image'
      - 'us-docker.pkg.dev/trans-airfoil-449223-q8/changedetection-repo/changedetection'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'

logsBucket: "gs://versterrewebsitechange/data"  # Store build logs in this bucket


