steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/trans-airfoil-449223-q8/changedetection', '.']

  # Step 2: Push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/trans-airfoil-449223-q8/changedetection']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'changedetection'
      - '--image'
      - 'gcr.io/trans-airfoil-449223-q8/changedetection'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1' # Change to your preferred region
      - '--allow-unauthenticated' # Remove if you want authentication

images:
  - 'gcr.io/trans-airfoil-449223-q8/changedetection'

options:
  logging: CLOUD_LOGGING_ONLY  # Optional: Logs are stored only in Cloud Logging
  logsBucket: "gs://versterrewebsitechange/data"
